import React, { useState, useEffect } from "react";
import {
  ShieldAlert, AlertTriangle, Users, Route, Activity, CloudRain,
  MapPin, Clock, ArrowUpRight, TrendingUp, RefreshCw, FileText, CheckCircle2,
  Radio, Play, FastForward, Info, Sun, Zap
} from "lucide-react";
import {
  ResponsiveContainer, AreaChart, Area, XAxis, YAxis, Tooltip, CartesianGrid
} from "recharts";
import { api } from "../services/api";

export default function CommandCenter({
  onNavigateToMap,
  onNavigateToReports,
  onNavigateToWarnings,
  onSelectDistrict,
}) {
  const [overview, setOverview] = useState(null);
  const [locations, setLocations] = useState([]);
  const [warnings, setWarnings] = useState([]);
  const [fieldReports, setFieldReports] = useState([]);
  const [simulatorStatus, setSimulatorStatus] = useState(null);
  const [loading, setLoading] = useState(true);
  const [simLoading, setSimLoading] = useState(false);

  const fetchData = async () => {
    try {
      const [ovRes, locRes, warnRes, repRes, simRes] = await Promise.all([
        api.getRiskOverview(),
        api.getRiskZones(),
        api.getWarnings(),
        api.getFieldReports(),
        api.getSimulatorStatus().catch(() => null),
      ]);
      setOverview(ovRes);
      setLocations(locRes);
      setWarnings(warnRes);
      setFieldReports(repRes);
      setSimulatorStatus(simRes);
    } catch (err) {
      console.error("Command center data load error:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
    const interval = setInterval(fetchData, 8000);
    return () => clearInterval(interval);
  }, []);

  const handleScenarioChange = async (scenario) => {
    setSimLoading(true);
    try {
      await api.setSimulatorScenario(scenario);
      await fetchData();
    } catch (err) {
      console.error("Failed to switch scenario:", err);
    } finally {
      setSimLoading(false);
    }
  };

  const handleTriggerTick = async () => {
    setSimLoading(true);
    try {
      await api.triggerSimulatorTick();
      await fetchData();
    } catch (err) {
      console.error("Failed to trigger simulation step:", err);
    } finally {
      setSimLoading(false);
    }
  };

  const activeScenario = simulatorStatus?.current_scenario || "DYNAMIC_CYCLE";

  return (
    <div className="p-4 md:p-6 space-y-6 max-w-7xl mx-auto text-slate-900 bg-slate-50 min-h-full">
      {/* PROMINENT DATA TRANSPARENCY NOTICE BANNER - LIGHT */}
      <div className="bg-amber-50 border border-amber-200 p-3.5 rounded-xl flex items-center justify-between gap-3 text-xs shadow-xs text-amber-900">
        <div className="flex items-center gap-2.5">
          <Info className="w-4 h-4 text-amber-600 flex-shrink-0" />
          <span>
            <strong className="font-semibold text-amber-950">DATA TRANSPARENCY NOTICE:</strong> Weather data is
            generated by an automated local simulation engine. All risk probabilities are calculated
            in real-time by the <strong>trained XGBoost ML model</strong>.
          </span>
        </div>
        <span className="hidden sm:inline-block px-2.5 py-0.5 rounded-full text-[10px] font-mono font-bold bg-amber-100 text-amber-800 border border-amber-300 flex-shrink-0">
          SIMULATED / DEMO MODE
        </span>
      </div>

      {/* TOP HEADER & LIVE SIMULATION CONTROL DOCK */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 border-b border-slate-200 pb-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="h-2 w-2 rounded-full bg-blue-600"></span>
            <span className="text-xs font-mono text-blue-600 font-semibold uppercase tracking-widest">
              Regional Operations Dashboard
            </span>
          </div>
          <h1 className="text-2xl md:text-3xl font-extrabold text-slate-900 tracking-tight mt-1">
            Command Center
          </h1>
          <p className="text-xs text-slate-500 mt-0.5">
            Real-time Landslide Hazard Monitoring & Early Warning Decision Support for Northeast India
          </p>
        </div>

        {/* Live Simulation Dock */}
        <div className="bg-white border border-slate-200 p-2 rounded-xl flex flex-wrap items-center gap-2 shadow-xs">
          <div className="text-[11px] font-mono text-slate-600 pr-2 border-r border-slate-200 flex items-center gap-1.5 font-medium">
            <Radio className="w-3.5 h-3.5 text-blue-600 animate-pulse" />
            <span>Tick #{simulatorStatus?.tick_count ?? 0}</span>
          </div>

          <div className="flex items-center gap-1">
            <button
              onClick={() => handleScenarioChange("MONSOON_SURGE")}
              className={`px-2.5 py-1 rounded-lg text-[11px] font-semibold transition-all ${
                activeScenario === "MONSOON_SURGE"
                  ? "bg-red-50 text-red-700 border border-red-200 shadow-xs"
                  : "bg-slate-100 text-slate-600 hover:bg-slate-200"
              }`}
              title="Simulate continuous monsoon rainfall surge"
            >
              🌧️ Monsoon Surge
            </button>

            <button
              onClick={() => handleScenarioChange("FLASH_CLOUDBURST")}
              className={`px-2.5 py-1 rounded-lg text-[11px] font-semibold transition-all ${
                activeScenario === "FLASH_CLOUDBURST"
                  ? "bg-orange-50 text-orange-700 border border-orange-200 shadow-xs"
                  : "bg-slate-100 text-slate-600 hover:bg-slate-200"
              }`}
              title="Simulate sudden localized cloudburst"
            >
              ⚡ Cloudburst
            </button>

            <button
              onClick={() => handleScenarioChange("DRY_STABILIZATION")}
              className={`px-2.5 py-1 rounded-lg text-[11px] font-semibold transition-all ${
                activeScenario === "DRY_STABILIZATION"
                  ? "bg-emerald-50 text-emerald-700 border border-emerald-200 shadow-xs"
                  : "bg-slate-100 text-slate-600 hover:bg-slate-200"
              }`}
              title="Simulate dry weather & slope drainage"
            >
              ☀️ Dry Spell
            </button>

            <button
              onClick={() => handleScenarioChange("DYNAMIC_CYCLE")}
              className={`px-2.5 py-1 rounded-lg text-[11px] font-semibold transition-all ${
                activeScenario === "DYNAMIC_CYCLE"
                  ? "bg-blue-50 text-blue-700 border border-blue-200 shadow-xs"
                  : "bg-slate-100 text-slate-600 hover:bg-slate-200"
              }`}
              title="Continuous diurnal waveform"
            >
              🔄 Harmonic
            </button>
          </div>

          <button
            onClick={handleTriggerTick}
            disabled={simLoading}
            className="px-3 py-1 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-[11px] font-semibold flex items-center gap-1 transition shadow-xs"
            title="Step weather forward immediately"
          >
            <FastForward className="w-3 h-3" />
            Step
          </button>
        </div>
      </div>

      {/* KPI METRICS GRID */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {/* Total Monitored Zones */}
        <div className="bg-white border border-slate-200 p-4 rounded-xl shadow-xs relative overflow-hidden">
          <div className="text-slate-500 text-xs font-semibold uppercase tracking-wider flex items-center justify-between">
            <span>Monitored Locations</span>
            <MapPin className="w-4 h-4 text-blue-600" />
          </div>
          <div className="text-3xl font-extrabold text-slate-900 font-mono mt-2">
            {overview?.total_monitored_locations ?? 10}
          </div>
          <div className="text-[11px] text-slate-500 mt-1 flex items-center gap-1.5">
            <span className="text-blue-600 font-semibold">6 States</span> across Northeast India
          </div>
        </div>

        {/* Critical Alerts */}
        <div className="bg-white border border-red-200 p-4 rounded-xl shadow-xs relative overflow-hidden">
          <div className="text-red-700 text-xs font-semibold uppercase tracking-wider flex items-center justify-between">
            <span>Critical Hotspots</span>
            <ShieldAlert className="w-4 h-4 text-red-600 animate-pulse" />
          </div>
          <div className="text-3xl font-extrabold text-red-600 font-mono mt-2">
            {overview?.critical_count ?? 0}
          </div>
          <div className="text-[11px] text-slate-500 mt-1">
            <span className="text-red-600 font-bold">{overview?.critical_count ?? 0} Critical</span> +{" "}
            <span className="text-orange-600 font-bold">{overview?.high_count ?? 0} High Risk</span>
          </div>
        </div>

        {/* Active Warnings */}
        <div className="bg-white border border-amber-200 p-4 rounded-xl shadow-xs relative overflow-hidden">
          <div className="text-amber-800 text-xs font-semibold uppercase tracking-wider flex items-center justify-between">
            <span>Active Warnings</span>
            <AlertTriangle className="w-4 h-4 text-amber-600" />
          </div>
          <div className="text-3xl font-extrabold text-amber-600 font-mono mt-2">
            {overview?.active_warnings_count ?? warnings.length}
          </div>
          <div className="text-[11px] text-slate-500 mt-1">
            <span>Evaluated from XGBoost Model</span>
          </div>
        </div>

        {/* Exposed Population */}
        <div className="bg-white border border-slate-200 p-4 rounded-xl shadow-xs relative overflow-hidden">
          <div className="text-slate-500 text-xs font-semibold uppercase tracking-wider flex items-center justify-between">
            <span>Exposed Population</span>
            <Users className="w-4 h-4 text-blue-600" />
          </div>
          <div className="text-3xl font-extrabold text-slate-900 font-mono mt-2">
            {overview?.exposed_population_total
              ? (overview.exposed_population_total / 1000000).toFixed(2) + "M"
              : "2.84M"}
          </div>
          <div className="text-[11px] text-slate-500 mt-1">
            In monitored mountain drainage basins
          </div>
        </div>
      </div>

      {/* RISK DISTRIBUTION BAR */}
      <div className="bg-white border border-slate-200 p-4 rounded-xl shadow-xs space-y-3">
        <div className="flex items-center justify-between text-xs font-bold text-slate-800">
          <span className="flex items-center gap-2">
            <Activity className="w-4 h-4 text-blue-600" />
            Regional Hazard Tier Breakdown
          </span>
          <span className="text-slate-500 font-mono">10 Total Districts Monitored</span>
        </div>

        <div className="w-full h-3 bg-slate-100 rounded-full overflow-hidden flex border border-slate-200">
          <div
            className="bg-emerald-500 h-full transition-all duration-500"
            style={{ width: `${((overview?.low_count || 0) / 10) * 100}%` }}
            title={`Low: ${overview?.low_count || 0}`}
          ></div>
          <div
            className="bg-amber-500 h-full transition-all duration-500"
            style={{ width: `${((overview?.moderate_count || 0) / 10) * 100}%` }}
            title={`Moderate: ${overview?.moderate_count || 0}`}
          ></div>
          <div
            className="bg-orange-500 h-full transition-all duration-500"
            style={{ width: `${((overview?.high_count || 0) / 10) * 100}%` }}
            title={`High: ${overview?.high_count || 0}`}
          ></div>
          <div
            className="bg-red-500 h-full transition-all duration-500"
            style={{ width: `${((overview?.critical_count || 0) / 10) * 100}%` }}
            title={`Critical: ${overview?.critical_count || 0}`}
          ></div>
        </div>

        <div className="grid grid-cols-4 gap-2 text-center text-xs font-mono pt-1">
          <div className="text-emerald-700 font-medium">
            <span className="font-bold">{overview?.low_count ?? 0}</span> Safe / Low
          </div>
          <div className="text-amber-700 font-medium">
            <span className="font-bold">{overview?.moderate_count ?? 0}</span> Moderate
          </div>
          <div className="text-orange-700 font-medium">
            <span className="font-bold">{overview?.high_count ?? 0}</span> High
          </div>
          <div className="text-red-700 font-medium">
            <span className="font-bold">{overview?.critical_count ?? 0}</span> Critical
          </div>
        </div>
      </div>

      {/* MAIN CONTENT SPLIT: Critical Hotspots & 24h Trend Chart */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Critical & High Risk Hotspots (5 cols) */}
        <div className="lg:col-span-5 bg-white border border-slate-200 p-5 rounded-xl shadow-xs space-y-4 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between mb-3">
              <h2 className="text-sm font-bold text-slate-900 uppercase tracking-wider flex items-center gap-2">
                <ShieldAlert className="w-4 h-4 text-red-600" />
                Vulnerable Hotspot Districts
              </h2>
              <span className="text-[10px] font-mono text-blue-600 font-semibold">Model-Evaluated Index</span>
            </div>

            <div className="space-y-2.5 max-h-[340px] overflow-y-auto pr-1">
              {locations
                .slice()
                .sort((a, b) => b.baseline_risk_score - a.baseline_risk_score)
                .map((loc) => {
                  const score = loc.baseline_risk_score;
                  const isCrit = score >= 75;
                  const isHigh = score >= 50 && score < 75;

                  return (
                    <div
                      key={loc.id}
                      onClick={() => {
                        if (onSelectDistrict) onSelectDistrict(loc.id);
                        if (onNavigateToMap) onNavigateToMap();
                      }}
                      className={`p-3 rounded-xl border transition-all cursor-pointer flex items-center justify-between ${
                        isCrit
                          ? "bg-red-50/70 border-red-200 hover:bg-red-100/60"
                          : isHigh
                          ? "bg-orange-50/60 border-orange-200 hover:bg-orange-100/60"
                          : "bg-slate-50 border-slate-200 hover:bg-slate-100"
                      }`}
                    >
                      <div>
                        <div className="font-bold text-slate-900 text-xs flex items-center gap-1.5">
                          {loc.name}
                          {isCrit && (
                            <span className="px-1.5 py-0.2 text-[9px] font-bold bg-red-600 text-white rounded">
                              RED ALERT
                            </span>
                          )}
                        </div>
                        <div className="text-[11px] text-slate-500 mt-0.5">
                          {loc.state} • Pop: {loc.population_exposed?.toLocaleString()}
                        </div>
                      </div>

                      <div className="text-right">
                        <div
                          className={`text-sm font-mono font-extrabold ${
                            isCrit
                              ? "text-red-600"
                              : isHigh
                              ? "text-orange-600"
                              : "text-amber-600"
                          }`}
                        >
                          {score}%
                        </div>
                        <div className="text-[10px] text-slate-500 font-mono">
                          Rain: {loc.latest_weather?.rainfall_24h_mm ?? "—"}mm
                        </div>
                      </div>
                    </div>
                  );
                })}
            </div>
          </div>

          <button
            onClick={onNavigateToMap}
            className="w-full py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-semibold tracking-wide transition shadow-xs flex items-center justify-center gap-2 mt-3"
          >
            Launch Live Risk Map
            <ArrowUpRight className="w-4 h-4" />
          </button>
        </div>

        {/* 24-Hour Regional Risk Trajectory Recharts (7 cols) */}
        <div className="lg:col-span-7 bg-white border border-slate-200 p-5 rounded-xl shadow-xs space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="text-sm font-bold text-slate-900 uppercase tracking-wider flex items-center gap-2">
              <TrendingUp className="w-4 h-4 text-blue-600" />
              24-Hour Regional Landslide Risk Trajectory
            </h2>
            <span className="text-[10px] font-mono text-slate-500">Simulation Stream</span>
          </div>

          <div className="h-64 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart
                data={
                  overview?.recent_trend || [
                    { time: "00:00", avg_risk: 41.2 },
                    { time: "04:00", avg_risk: 43.5 },
                    { time: "08:00", avg_risk: 49.0 },
                    { time: "12:00", avg_risk: 54.8 },
                    { time: "16:00", avg_risk: 58.2 },
                    { time: "Now", avg_risk: 61.4 },
                  ]
                }
                margin={{ top: 10, right: 10, left: -20, bottom: 0 }}
              >
                <defs>
                  <linearGradient id="riskGradientLight" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#2563eb" stopOpacity={0.25} />
                    <stop offset="95%" stopColor="#2563eb" stopOpacity={0.0} />
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                <XAxis dataKey="time" stroke="#64748b" fontSize={11} />
                <YAxis stroke="#64748b" fontSize={11} domain={[0, 100]} />
                <Tooltip
                  contentStyle={{
                    backgroundColor: "#ffffff",
                    borderColor: "#cbd5e1",
                    borderRadius: "8px",
                    color: "#0f172a",
                    fontSize: "12px",
                    boxShadow: "0 4px 6px -1px rgba(0,0,0,0.1)",
                  }}
                />
                <Area
                  type="monotone"
                  dataKey="avg_risk"
                  stroke="#2563eb"
                  strokeWidth={2.5}
                  fillOpacity={1}
                  fill="url(#riskGradientLight)"
                  name="Mean Risk %"
                />
              </AreaChart>
            </ResponsiveContainer>
          </div>

          <div className="grid grid-cols-3 gap-2 text-xs border-t border-slate-200 pt-3">
            <div className="p-2.5 bg-slate-50 rounded-lg border border-slate-200">
              <span className="text-[10px] text-slate-500 font-medium block">Monsoon Crest Peak</span>
              <span className="font-mono font-extrabold text-red-600 text-sm">
                {locations.length > 0
                  ? `${Math.max(...locations.map((l) => l.baseline_risk_score))}%`
                  : "78.0%"}
              </span>
            </div>
            <div className="p-2.5 bg-slate-50 rounded-lg border border-slate-200">
              <span className="text-[10px] text-slate-500 font-medium block">Active Scenario</span>
              <span className="font-mono font-bold text-blue-700">{activeScenario}</span>
            </div>
            <div className="p-2.5 bg-slate-50 rounded-lg border border-slate-200">
              <span className="text-[10px] text-slate-500 font-medium block">Corridor Alert Status</span>
              <span className="font-mono font-bold text-amber-700">NH-13 Monitored</span>
            </div>
          </div>
        </div>
      </div>

      {/* BOTTOM ROW: Active Early Warnings & Field Intelligence Feed */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Active Early Warnings (6 cols) */}
        <div className="lg:col-span-6 bg-white border border-slate-200 p-5 rounded-xl shadow-xs space-y-3">
          <div className="flex items-center justify-between">
            <h2 className="text-sm font-bold text-slate-900 uppercase tracking-wider flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 text-amber-600" />
              Active Early Warnings ({warnings.length})
            </h2>
            <span className="text-[10px] font-mono text-slate-500">Auto-Generated by Thresholds</span>
          </div>

          <div className="space-y-2.5 max-h-56 overflow-y-auto pr-1">
            {warnings.map((w) => (
              <div
                key={w.id}
                className="p-3 bg-slate-50 rounded-xl border border-slate-200 flex items-start justify-between text-xs gap-3"
              >
                <div>
                  <div className="flex items-center gap-2">
                    <span
                      className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                        w.severity === "CRITICAL"
                          ? "bg-red-100 text-red-700 border border-red-200"
                          : "bg-orange-100 text-orange-700 border border-orange-200"
                      }`}
                    >
                      {w.severity}
                    </span>
                    <span className="font-bold text-slate-900">{w.location_name}</span>
                  </div>
                  <p className="text-[11px] text-slate-600 mt-1 leading-relaxed">
                    {w.recommended_action}
                  </p>
                  <div className="text-[10px] text-slate-500 font-mono mt-1">
                    Triggers: {w.main_factors}
                  </div>
                </div>

                <div className="text-right flex-shrink-0">
                  <span className="font-mono font-bold text-amber-700 text-sm">{w.risk_probability}%</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Field Reports Feed (6 cols) */}
        <div className="lg:col-span-6 bg-white border border-slate-200 p-5 rounded-xl shadow-xs space-y-3">
          <div className="flex items-center justify-between">
            <h2 className="text-sm font-bold text-slate-900 uppercase tracking-wider flex items-center gap-2">
              <FileText className="w-4 h-4 text-blue-600" />
              Ground Field Reports ({fieldReports.length})
            </h2>
            {onNavigateToReports && (
              <button
                onClick={onNavigateToReports}
                className="text-[11px] font-semibold text-blue-600 hover:text-blue-700 flex items-center gap-1 transition"
              >
                Open Portal <ArrowUpRight className="w-3.5 h-3.5" />
              </button>
            )}
          </div>

          <div className="space-y-2.5 max-h-56 overflow-y-auto pr-1">
            {fieldReports.map((r) => (
              <div
                key={r.id}
                onClick={onNavigateToReports}
                className="p-3 bg-slate-50 hover:bg-slate-100/80 rounded-xl border border-slate-200 cursor-pointer transition text-xs space-y-1"
              >
                <div className="flex items-center justify-between">
                  <span className="font-bold text-slate-900">{r.location_name}</span>
                  <span
                    className={`px-2 py-0.2 rounded text-[10px] font-bold ${
                      r.verification_status === "VERIFIED"
                        ? "bg-emerald-100 text-emerald-700"
                        : "bg-amber-100 text-amber-800"
                    }`}
                  >
                    {r.verification_status}
                  </span>
                </div>
                <p className="text-slate-600 text-[11px] leading-relaxed">{r.description}</p>
                <div className="flex items-center justify-between text-[10px] text-slate-500 font-mono pt-1">
                  <span>Hazard: {r.hazard_type.replace("_", " ")}</span>
                  <span>Role: {r.reporter_role}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
